name: Build All

on:
  push:
    branches: [ master ]
    paths:
    - 'src/**'
    - '.github/workflows/ci_build.yml'
  pull_request:
    branches: [ master ]
    paths:
    - 'src/**'
    - '.github/workflows/ci_build.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.0
    - name: Install dependencies
      run: dotnet restore src/OutboxPattern.Demo.sln
    - name: Build
      run: dotnet build src/OutboxPattern.Demo.sln --configuration Release --no-restore
    # - name: Test
    #   run: dotnet test src/OutboxPattern.Demo.sln --no-restore --verbosity normal
